/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/ironcore-dev/oob/api/v1alpha1"
	apiv1alpha1 "github.com/ironcore-dev/oob/applyconfiguration/api/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=core, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("OOB"):
		return &apiv1alpha1.OOBApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OOBSpec"):
		return &apiv1alpha1.OOBSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OOBStatus"):
		return &apiv1alpha1.OOBStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TagSpec"):
		return &apiv1alpha1.TagSpecApplyConfiguration{}

	}
	return nil
}
