version: 2
updates:
#- package-ecosystem: gomod
#  directory: "/"
#  schedule:
#    interval: daily
#  reviewers:
#  - 5kt
#  - Gchbg
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - 5kt
  - Gchbg
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - 5kt
  - Gchbg
