version: 2
updates:
#- package-ecosystem: gomod
#  directory: "/"
#  schedule:
#    interval: daily
#  commit-message:
#    prefix: ""
#  reviewers:
#  - Gchbg
#  - 5kt
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: ""
  reviewers:
  - Gchbg
  - 5kt
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: ""
  reviewers:
  - Gchbg
  - 5kt
