apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - kustomizeconfig.yaml

bases:
- ../default
- ../certmanager
- ../consoleservice

vars:
  - name: SERVICE_NAMESPACE
    objref:
      kind: Service
      version: v1
      name: oob-console
    fieldref:
      fieldpath: metadata.namespace
  - name: SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: oob-console

patchesStrategicMerge:
- cert_patch.yaml

patches:
  - target:
      group: apps
      kind: Deployment
      name: oob-controller-manager
      namespace: system 
      version: v1
    path: args_patch.yaml
