apiVersion: v1
kind: Service
metadata:
  name: oob-console
  namespace: system
spec:
  ports:
    - port: 12319 
      protocol: TCP
      targetPort: 12319
  selector:
    control-plane: controller-manager
  type: ClusterIP
