# permissions for end users to edit oobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oob-editor-role
rules:
- apiGroups:
  - ironcore.dev
  resources:
  - oobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ironcore.dev
  resources:
  - oobs/status
  verbs:
  - get
