---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - compute.api.ironcore.dev
  resources:
  - machinepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.api.ironcore.dev
  resources:
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.onmetal.de
  resources:
  - ips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.onmetal.de
  resources:
  - ips/status
  verbs:
  - get
- apiGroups:
  - ironcore.dev
  resources:
  - oobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ironcore.dev
  resources:
  - oobs/finalizers
  verbs:
  - update
- apiGroups:
  - ironcore.dev
  resources:
  - oobs/status
  verbs:
  - get
  - patch
  - update
