/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OOBSpecApplyConfiguration represents an declarative configuration of the OOBSpec type for use
// with apply.
type OOBSpecApplyConfiguration struct {
	LocatorLED *string `json:"locatorLED,omitempty"`
	Power      *string `json:"power,omitempty"`
	Reset      *string `json:"reset,omitempty"`
	Filler     *int64  `json:"filler,omitempty"`
}

// OOBSpecApplyConfiguration constructs an declarative configuration of the OOBSpec type for use with
// apply.
func OOBSpec() *OOBSpecApplyConfiguration {
	return &OOBSpecApplyConfiguration{}
}

// WithLocatorLED sets the LocatorLED field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocatorLED field is set to the value of the last call.
func (b *OOBSpecApplyConfiguration) WithLocatorLED(value string) *OOBSpecApplyConfiguration {
	b.LocatorLED = &value
	return b
}

// WithPower sets the Power field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Power field is set to the value of the last call.
func (b *OOBSpecApplyConfiguration) WithPower(value string) *OOBSpecApplyConfiguration {
	b.Power = &value
	return b
}

// WithReset sets the Reset field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reset field is set to the value of the last call.
func (b *OOBSpecApplyConfiguration) WithReset(value string) *OOBSpecApplyConfiguration {
	b.Reset = &value
	return b
}

// WithFiller sets the Filler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Filler field is set to the value of the last call.
func (b *OOBSpecApplyConfiguration) WithFiller(value int64) *OOBSpecApplyConfiguration {
	b.Filler = &value
	return b
}
