/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OOBSpecApplyConfiguration represents an declarative configuration of the OOBSpec type for use
// with apply.
type OOBSpecApplyConfiguration struct {
	LocatorLED *string `json:"locatorLED,omitempty"`
	Power      *string `json:"power,omitempty"`
	Reset      *string `json:"reset,omitempty"`
	Filler     *int64  `json:"filler,omitempty"`
}

// OOBSpecApplyConfiguration constructs an declarative configuration of the OOBSpec type for use with
// apply.
func OOBSpec() *OOBSpecApplyConfiguration {
	return &OOBSpecApplyConfiguration{}
}

// WithLocatorLED sets the LocatorLED field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocatorLED field is set to the value of the last call.
func (b *OOBSpecApplyConfiguration) WithLocatorLED(value string) *OOBSpecApplyConfiguration {
	b.LocatorLED = &value
	return b
}

// WithPower sets the Power field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Power field is set to the value of the last call.
func (b *OOBSpecApplyConfiguration) WithPower(value string) *OOBSpecApplyConfiguration {
	b.Power = &value
	return b
}

// WithReset sets the Reset field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reset field is set to the value of the last call.
func (b *OOBSpecApplyConfiguration) WithReset(value string) *OOBSpecApplyConfiguration {
	b.Reset = &value
	return b
}

// WithFiller sets the Filler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Filler field is set to the value of the last call.
func (b *OOBSpecApplyConfiguration) WithFiller(value int64) *OOBSpecApplyConfiguration {
	b.Filler = &value
	return b
}
