/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TagSpecApplyConfiguration represents an declarative configuration of the TagSpec type for use
// with apply.
type TagSpecApplyConfiguration struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// TagSpecApplyConfiguration constructs an declarative configuration of the TagSpec type for use with
// apply.
func TagSpec() *TagSpecApplyConfiguration {
	return &TagSpecApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *TagSpecApplyConfiguration) WithKey(value string) *TagSpecApplyConfiguration {
	b.Key = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *TagSpecApplyConfiguration) WithValue(value string) *TagSpecApplyConfiguration {
	b.Value = &value
	return b
}
