apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oob-cert
  namespace: system
spec:
  dnsNames:
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  secretName: $(SERVICE_NAME)-cert
