name: Lint Golang Codebase

on:
  release:
    types:
      - published
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request_target:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  golangci:
    name: lint
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Set up git redirect
        run: ./hack/setup-git-redirect.sh
        env:
          GITHUB_PAT: ${{ secrets.BOT_PAT }}
      - name: Run golang-ci
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
          args: --timeout 5m
